// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SmartScheduler.Infrastructure.Persistence;

#nullable disable

namespace SmartScheduler.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251107222306_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SmartScheduler.Domain.Entities.Contractor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<string>("FormattedId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("formatted_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Guid>("JobTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_type_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.Property<decimal>("Rating")
                        .HasPrecision(3, 1)
                        .HasColumnType("numeric(3,1)")
                        .HasColumnName("rating");

                    b.HasKey("Id");

                    b.HasIndex("FormattedId")
                        .IsUnique()
                        .HasDatabaseName("ix_contractors_formatted_id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_contractors_is_active");

                    b.HasIndex("JobTypeId")
                        .HasDatabaseName("ix_contractors_job_type_id");

                    b.HasIndex("Rating")
                        .HasDatabaseName("ix_contractors_rating");

                    b.ToTable("contractors", (string)null);
                });

            modelBuilder.Entity("SmartScheduler.Domain.Entities.Job", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AssignedContractorId")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_contractor_id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("customer_id");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("customer_name");

                    b.Property<DateTime>("DesiredDate")
                        .HasColumnType("date")
                        .HasColumnName("desired_date");

                    b.Property<TimeOnly?>("DesiredTime")
                        .HasColumnType("time")
                        .HasColumnName("desired_time");

                    b.Property<decimal>("EstimatedDurationHours")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("estimated_duration_hours");

                    b.Property<string>("FormattedId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("formatted_id");

                    b.Property<Guid>("JobTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_type_id");

                    b.Property<DateTime?>("ScheduledStartTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_start_time");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("AssignedContractorId")
                        .HasDatabaseName("ix_jobs_assigned_contractor_id");

                    b.HasIndex("DesiredDate")
                        .HasDatabaseName("ix_jobs_desired_date");

                    b.HasIndex("FormattedId")
                        .IsUnique()
                        .HasDatabaseName("ix_jobs_formatted_id");

                    b.HasIndex("JobTypeId")
                        .HasDatabaseName("ix_jobs_job_type_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_jobs_status");

                    b.ToTable("jobs", (string)null);
                });

            modelBuilder.Entity("SmartScheduler.Domain.Entities.JobType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_job_types_is_active");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_job_types_name");

                    b.ToTable("job_types", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            Description = "Specializes in ceramic, porcelain, and natural stone tile installation",
                            IsActive = true,
                            Name = "Tile Installer"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            Description = "Specializes in carpet installation and replacement",
                            IsActive = true,
                            Name = "Carpet Installer"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            Description = "Specializes in hardwood floor installation, refinishing, and repair",
                            IsActive = true,
                            Name = "Hardwood Specialist"
                        });
                });

            modelBuilder.Entity("SmartScheduler.Domain.Entities.WeeklySchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ContractorId")
                        .HasColumnType("uuid")
                        .HasColumnName("contractor_id");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer")
                        .HasColumnName("day_of_week");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time")
                        .HasColumnName("end_time");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time")
                        .HasColumnName("start_time");

                    b.HasKey("Id");

                    b.HasIndex("ContractorId")
                        .HasDatabaseName("ix_weekly_schedules_contractor_id");

                    b.HasIndex("ContractorId", "DayOfWeek")
                        .HasDatabaseName("ix_weekly_schedules_contractor_day");

                    b.ToTable("weekly_schedules", (string)null);
                });

            modelBuilder.Entity("SmartScheduler.Domain.Entities.Contractor", b =>
                {
                    b.HasOne("SmartScheduler.Domain.Entities.JobType", null)
                        .WithMany()
                        .HasForeignKey("JobTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("SmartScheduler.Domain.ValueObjects.Location", "BaseLocation", b1 =>
                        {
                            b1.Property<Guid>("ContractorId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Address")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("base_address");

                            b1.Property<double>("Latitude")
                                .HasPrecision(9, 6)
                                .HasColumnType("double precision")
                                .HasColumnName("base_latitude");

                            b1.Property<double>("Longitude")
                                .HasPrecision(9, 6)
                                .HasColumnType("double precision")
                                .HasColumnName("base_longitude");

                            b1.HasKey("ContractorId");

                            b1.ToTable("contractors");

                            b1.WithOwner()
                                .HasForeignKey("ContractorId");
                        });

                    b.Navigation("BaseLocation")
                        .IsRequired();
                });

            modelBuilder.Entity("SmartScheduler.Domain.Entities.Job", b =>
                {
                    b.HasOne("SmartScheduler.Domain.Entities.Contractor", null)
                        .WithMany()
                        .HasForeignKey("AssignedContractorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SmartScheduler.Domain.Entities.JobType", null)
                        .WithMany()
                        .HasForeignKey("JobTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("SmartScheduler.Domain.ValueObjects.Location", "Location", b1 =>
                        {
                            b1.Property<Guid>("JobId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Address")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("location_address");

                            b1.Property<double>("Latitude")
                                .HasPrecision(9, 6)
                                .HasColumnType("double precision")
                                .HasColumnName("location_latitude");

                            b1.Property<double>("Longitude")
                                .HasPrecision(9, 6)
                                .HasColumnType("double precision")
                                .HasColumnName("location_longitude");

                            b1.HasKey("JobId");

                            b1.ToTable("jobs");

                            b1.WithOwner()
                                .HasForeignKey("JobId");
                        });

                    b.Navigation("Location")
                        .IsRequired();
                });

            modelBuilder.Entity("SmartScheduler.Domain.Entities.WeeklySchedule", b =>
                {
                    b.HasOne("SmartScheduler.Domain.Entities.Contractor", null)
                        .WithMany()
                        .HasForeignKey("ContractorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
